spring:
  datasource:
    username: root
    password: 1234567
    url: jdbc:mysql://localhost:3306/webtest?useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true 
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: edu.swjtuhc.demo-2.mapper